[package]
name = "eisen"
version = "0.1.0"
edition = "2021"
authors = ["Johann Scott <johann@somecollagist.com>"]

[lib]
crate-type = ["staticlib"]
path = "src/entry.rs"

[dependencies]
x86_64 = "0.14.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]